#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Created on Wed Feb 08:50:21 2023
@author: rivera
"""
from sys import argv as args
import os
from csv_diff import load_csv, compare

TEST_FILES: list = ['test01.csv',
                    'test02.csv',
                    'test03.csv',
                    'test04.csv',
                    'test05.csv']
REQUIRED_FILES: list = ['music_manager', 'top_songs_1999.csv', 'top_songs_2009.csv', 'top_songs_2019.csv']
TESTER_PROGRAM_NAME: str = 'tester'
PROGRAM_ARGS: str = '<question(e.g.,1,2,3,4,5)>'
USAGE_MSG: str = f'Usage: ./{TESTER_PROGRAM_NAME} {PROGRAM_ARGS} or ./{TESTER_PROGRAM_NAME}'


def required_files_exist() -> bool:
    """Determines whether there are missing files.
            Returns
            -------
                bool
    """
    exist: bool = True
    for file in REQUIRED_FILES + TEST_FILES:
        if not os.path.isfile(file):
            exist = False
            break
    return exist


def print_message(is_error: bool, message: str) -> None:
    """Prints a message to stdout.
            Parameters
            ----------
                is_error : bool, required
                    Indicates whether the message is an error.
                message : str, required
                    The message to be printed out.
    """
    message_type: str = 'ERROR' if is_error else 'INFO'
    print(f'[{TESTER_PROGRAM_NAME}] ({message_type}): {message}')


def generate_execution_commands(question: str) -> list:
    """Generates the execution commands for the tests.
            Parameters
            ----------
                question : str, required
                    The question for the commands to be generated. None if all test cases should be generated.
            Returns
            -------
                list
                    A list with all the commands generated.
    """
    commands: list = []
    commands.append('./music_manager --sortBy=popularity --display=10 --files=top_songs_1999.csv')
    commands.append('./music_manager --sortBy=energy --display=5 --files=top_songs_1999.csv')
    commands.append('./music_manager --sortBy=danceability --display=3 --files=top_songs_1999.csv')
    commands.append('./music_manager --sortBy=popularity --display=3 --files=top_songs_2009.csv')
    commands.append('./music_manager --sortBy=danceability --display=5 --files=top_songs_2019.csv')
    number: int = -1
    if question is not None:
        number = int(question) - 1
    commands = [commands[number]] if number >= 0 else commands
    return commands


def validate_tests(execution_commands: list, question: str) -> None:
    """Generates the execution commands for the tests.
            Parameters
            ----------
                execution_commands : list, required
                    The generated commands.
                question : str, required
                    The question for the commands to be generated. None if all test cases should be generated.
    """
    separator: str = '----------------------------------------'
    print_message(is_error=False, message=f'Tests to run: {len(execution_commands)}')
    tests_passed: int = 0
    result = ''
    for i in range(len(execution_commands)):
        test: int = int(question) if question is not None else i + 1
        print_message(is_error=False, message=f'|Test {test}|' + separator)
        command: str = execution_commands[i]
        required: list = [f'output.csv']
        # delete existing files
        for required_file in required:
            if os.path.isfile(required_file):
                os.remove(required_file)
        test_pass: bool = True
        print_message(is_error=False, message=f'Attempting: {command}')
        # execute command
        os.system(command=command)
        # validate generated files (csv)
        if not os.path.isfile(required[0]):
            print_message(is_error=False, message=f'music_manager should generate {required[0]} for this test.')
            test_pass = False
        else:
            # read csvs
            produced_data = load_csv(open(required[0], encoding='utf-8-sig'))
            expected_data = load_csv(open(f'test0{test}.csv', encoding='utf-8-sig'))
            # obtain the differences
            result = compare(produced_data, expected_data)
            order_differences: bool = False
            # compare
            if len(result['added']) > 0 or len(result['removed']) > 0 or len(result['changed']) > 0 or len(
                    result['columns_added']) > 0 or len(result['columns_removed']) > 0:
                test_pass = False
            else:
                # validate order
                produced_elements: list[tuple] = []
                expected_elements: list[tuple] = []
                try:
                    # produced
                    for key in produced_data.keys():
                        value: dict = produced_data[key]
                        produced_elements.append((value['song']))
                    # expected
                    for key in expected_data.keys():
                        value: dict = expected_data[key]
                        expected_elements.append((value['song']))
                    # verify order
                    for j in range(len(produced_elements)):
                        produced: tuple = produced_elements[j]
                        expected: tuple = expected_elements[j]
                        if not produced == expected:
                            test_pass = False
                            order_differences = True
                            break
                except:
                    test_pass = False
        print_message(is_error=False, message=f'TEST PASSED: {test_pass}')
        if not test_pass and os.path.isfile(required[0]):
            if not order_differences:
                print_message(is_error=False, message=f'DIFFERENCES: {result}')
            else:
                print_message(is_error=False, message=f'DIFFERENCES: wrong order in rows.')
        if test_pass:
            tests_passed += 1
    print_message(is_error=False, message=separator + '--------')
    print_message(is_error=False, message=f'TESTS PASSED: {tests_passed}/{len(execution_commands)}')


def main():
    """Main entry point of the program."""
    if len(args) - 1 > len(PROGRAM_ARGS.split(" ")):
        print_message(is_error=True, message=USAGE_MSG)
    else:
        question: str = None
        if len(args) != 1:
            question = args[1]
        # validate required filess
        if not required_files_exist():
            print_message(is_error=True, message=f'Required files: {REQUIRED_FILES + TEST_FILES}')
        else:
            # validate args
            valid_args: bool = True
            try:
                if question is not None:
                    question_int: int = int(question)
                    if question_int not in [1, 2, 3, 4, 5]:
                        valid_args = False
            except ValueError:
                valid_args = False
            if valid_args:
                commands: str = generate_execution_commands(question=question)
                validate_tests(execution_commands=commands, question=question)
            else:
                print_message(is_error=True, message=USAGE_MSG)


if __name__ == '__main__':
    main()
